[package]
name = "endgame"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
base64 = "0.22.1"
# TODO: Use from crates
crypter = { git = "https://github.com/m-lima/crypter", branch = "master" }
openidconnect = { version = "4.0.1", features = ["reqwest-blocking"] }
rand = "0.9.2"
