[package]
name = "endgame"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
base64 = { version = "0.22.1", default-features = false, optional = true }
chacha20poly1305 = "0.10.1"

[features]
default = ["base64"]
base64 = ["dep:base64"]
