
[profile.ngx-debug]
inherits = "dev"

[profile.ngx-release]
inherits = "release"
strip = "none"

# compatibility with LIBC=-MT set in auto/cc/msvc
[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[env]
NGINX_BUILD_DIR = { value = ".", force = true, relative = true }
NGINX_SOURCE_DIR = "/home/celo/code/rust/endgame/configer"
